-- StomaDesk, PostgreSQL schema. The app runs this script at every start, so each statement is safe to repeat.
--
-- ClinicStore keeps the business rules. The database repeats only the ones that must hold when several
-- workstations share it: no double booking, one CNP per patient, unique receipt numbers, and nothing
-- deleted while other rows still point at it.
--
-- Enum columns hold the C# enum names as text (Scheduled, Done, Card ...), so a row reads the same in psql
-- as in the code. Money is plain numeric: the value comes back exactly as written, like in the XML file.
-- Times are timestamp without time zone: an appointment at 09:00 is 09:00 at the clinic, whatever the server.

CREATE EXTENSION IF NOT EXISTS btree_gist;   -- lets the EXCLUDE constraint on appointments compare doctor_id with =

-- The clinic's own details (printed on estimates). Always a single row.
CREATE TABLE IF NOT EXISTS clinic_info (
    id          integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    name        text,
    address     text,
    phone       text,
    fiscal_code text
);

CREATE TABLE IF NOT EXISTS doctors (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    specialty   text,
    active      boolean NOT NULL DEFAULT true,
    color_argb  integer NOT NULL
);

-- The price list.
CREATE TABLE IF NOT EXISTS procedures (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             text,
    name             text NOT NULL,
    price            numeric NOT NULL CHECK (price >= 0),
    duration_minutes integer NOT NULL CHECK (duration_minutes > 0),
    per_tooth        boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS patients (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name   text NOT NULL,
    first_name  text NOT NULL,
    cnp         text,
    birth_date  date,
    phone       text,
    email       text,
    address     text,
    allergies   text,
    notes       text,
    created_at  timestamp NOT NULL
);

-- One CNP per patient across all workstations; patients without a CNP are not compared.
CREATE UNIQUE INDEX IF NOT EXISTS patients_cnp_key ON patients (cnp) WHERE cnp <> '';

-- The odontogram. Only teeth that are not healthy are stored; no row means "Sănătos".
CREATE TABLE IF NOT EXISTS patient_teeth (
    patient_id  integer NOT NULL REFERENCES patients (id) ON DELETE CASCADE,
    tooth       integer NOT NULL CHECK (tooth BETWEEN 11 AND 48),
    state       text NOT NULL,
    note        text,
    PRIMARY KEY (patient_id, tooth)
);

CREATE TABLE IF NOT EXISTS appointments (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id       integer NOT NULL,
    doctor_id        integer NOT NULL,
    start_at         timestamp NOT NULL,
    duration_minutes integer NOT NULL CHECK (duration_minutes > 0),
    reason           text,
    status           text NOT NULL,
    reminder_sent    boolean NOT NULL DEFAULT false,
    CONSTRAINT appointments_patient_fk FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
    CONSTRAINT appointments_doctor_fk FOREIGN KEY (doctor_id) REFERENCES doctors (id),
    -- ClinicStore.FindConflict, enforced for every workstation at once: a doctor's appointments that are
    -- not cancelled may touch (the ranges are half-open, [start, end)) but never overlap.
    CONSTRAINT appointments_no_overlap EXCLUDE USING gist (
        doctor_id WITH =,
        tsrange(start_at, start_at + make_interval(mins => duration_minutes)) WITH &&
    ) WHERE (status <> 'Cancelled')
);

CREATE INDEX IF NOT EXISTS appointments_patient_idx ON appointments (patient_id);

-- Treatment plans. Name and price are copied from the price list when planned (see TreatmentItem), so there is
-- no foreign key to procedures: removing a price-list line must not touch plans the patient already accepted.
CREATE TABLE IF NOT EXISTS treatments (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id       integer NOT NULL,
    procedure_id     integer NOT NULL,
    procedure_name   text NOT NULL,
    tooth            integer,
    price            numeric NOT NULL,
    discount_percent numeric NOT NULL DEFAULT 0 CHECK (discount_percent BETWEEN 0 AND 100),
    status           text NOT NULL,
    doctor_id        integer,
    created_at       timestamp NOT NULL,
    completed_at     timestamp,
    CONSTRAINT treatments_patient_fk FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT treatments_doctor_fk FOREIGN KEY (doctor_id) REFERENCES doctors (id)
);

CREATE INDEX IF NOT EXISTS treatments_patient_idx ON treatments (patient_id);

-- Receipt numbers (CH-000042) come from a sequence, so two workstations never print the same number.
CREATE SEQUENCE IF NOT EXISTS receipt_numbers;

CREATE TABLE IF NOT EXISTS payments (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id  integer NOT NULL,
    paid_at     timestamp NOT NULL,
    amount      numeric NOT NULL CHECK (amount > 0),
    method      text NOT NULL,
    note        text,
    receipt_no  text NOT NULL,
    CONSTRAINT payments_patient_fk FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT payments_receipt_key UNIQUE (receipt_no)
);

CREATE INDEX IF NOT EXISTS payments_patient_idx ON payments (patient_id);
